export const tenExample1 = [
    "湯が沸いた  Yu ga waita - The water boiled",
    "沸騰する前に止めて  Futtou suru mae ni tomete - Stop before it boils",
    "やかんで水を 沸かす  Yakan de mizu o wakasu - Boiling water in a kettle",
    "沸騰している湯気がすごい  Futtou shiteiru yuge ga sugoi - The steam from boiling is intense",
    "沸騰すると音がする  Futtou suru to oto ga suru - There's a sound when it boils",
    "沸騰したらすぐ火を止めて  Futtou shitara sugu hi o tomete - Turn off the heat as soon as it boils",
    "沸騰するまで待って  Futtou suru made matte - Wait until it boils",
    "沸騰した熱いお湯がほしい  Futtou shita atsui oyu ga hoshii - I want boiling hot water",
    "沸騰する前に取り出して  Futtou suru mae ni toridashite - Take it out before it boils",
    "湯を沸かすときに火を強くする  Yu o wakasu toki ni hi o tsuyoku suru - Increase the heat when boiling water",
    "鍋で湯を 沸かしています  Nabe de yu o wakashiteimasu - Boiling water in the pot",];
export const tenExample2 = [
    "需要が高いです Juyou ga takai desu - The demand is high",
    "その商品は需要があります Sono shouhin wa juyou ga arimasu - There is demand for that product",
    "需要を満たす必要があります Juyou o mitasu hitsuyou ga arimasu - There is a need to meet the demand",
    "需要が急速に増えています Juyou ga kyuusoku ni fueteimasu - The demand is increasing rapidly",
    "需要予測が難しいです Juyou yosoku ga muzukashii desu - Forecasting demand is difficult",
    "そのサービスには需要がありますか？ Sono saabisu ni wa juyou ga arimasu ka? - Is there a demand for that service?",
    "需要に応じて製品を調整します Juyou ni oujite seihin o chousei shimasu - We adjust the products according to the demand",
    "需要を満たすために努力しています Juyou o mitasu tame ni doryoku shiteimasu. - We are making efforts to meet the demand",
    "需要が予想以上でした Juyou ga yosou ijou deshita. - The demand exceeded expectations",
    "需要が安定しています Juyou ga antei shiteimasu. - The demand is stable",];
export const tenExample3 = [
    "虫刺されで腫れた Mushi sasare de hareta - I got swollen from a bug bite",
    "目が腫れています Me ga harete imasu - My eyes are swollen",
    "喉が腫れているようだ Nodo ga harete iru you da - Looks like my throat is swollen",
    "けがで足が腫れました Kega de ashi ga hare mashita - My leg got swollen from the injury",
    "その蚊に刺されて腫れた Sono ka ni sasarete hareta - I got swollen from that mosquito bite",
    "手が腫れてて動かせない Te ga harete te ugokasenai - My hand is swollen, and I can't move it",
    "彼の体に腫瘍が見つかった Kare no karada ni shuyou ga mitsukatta - A tumor was found in his body",
    "腫れが引かない Hare ga hikanai - The swelling isn't going down",
    "腫瘍が原因で痛みが出ています Shuyou ga gen'in de itami ga dete imasu - Pain is occurring due to the tumor",
    "腫れ止めの薬を塗った Hare dome no kusuri o nutta - I applied some anti-swelling medicine",];
export const tenExample4 = [
    "彼は疾患を抱えています Kare wa shikkan o kakaete imasu - He has a medical condition",
    "疾患の症状が出てきた Shikkan no shoujou ga dete kita - The symptoms of the illness appeared",
    "疾病を治療する必要があります Shippei o chiryou suru hitsuyou ga arimasu - There is a need to treat the disease",
    "疾患の治療法を探しています Shikkan no chiryouhou o sagashite imasu - Looking for treatment options for the illness",
    "その疾患は遺伝的な要素がある Sono shikkan wa iden-teki na youso ga aru - That illness has a genetic component",
    "疾患の早期発見が重要です Shikkan no souki hakken ga juuyou desu - Early detection of the illness is important",
    "疾患のリスクを減らす方法を知りたい Shikkan no risuku o herasu houhou o shiritai - I want to know ways to reduce the risk of illness",
    "彼は病気で疾走している Kare wa byouki de shissou shite iru - He's running a fever due to sickness",
    "その疾患はかなり重篤です Sono shikkan wa kanari jutoku desu - That illness is quite severe",
    "疾病にかかるのを予防するために手を洗いましょう Shippei ni kakaru no o yobou suru tame ni te o araimashou - Let's wash our hands to prevent illness"];
export const tenExample5 = [
    "匿名 で投稿することができます Tokumei de toukou suru koto ga dekimasu - You can post anonymously",
    "匿名性 を保つために、偽名を使うことがあります Tokumei-sei o tamotsu tame ni, gimei o tsukau koto ga arimasu - To maintain anonymity, one may use a false name",
    "匿名性を重んじる人もいます Tokumeisei o omonjiru hito mo imasu. - There are people who value anonymity",
    "彼は匿名でそのフォーラムに投稿した Kare wa tokumei de sono fo-ramu ni toukou shita - He posted on that forum anonymously",
    "私は匿名の手紙を受け取ったことがあります Watashi wa tokumei no tegami o uketotta koto ga arimasu - I have received an anonymous letter before",
    "匿名性を保つことはオンラインのセキュリティに関して重要です Tokumeisei o tamotsu koto wa onrain no sekuriti ni kan shite juuyou desu - Maintaining anonymity is important for online security",
    "そのウェブサイトでは、匿名で質問をすることができます Sono webusaito de wa, tokumei de shitsumon o suru koto ga dekimasu - On that website, you can ask questions anonymously",
    "匿名性を守るために、プライバシー設定を確認しましょう Tokumeisei o mamoru tame ni, puraibashii settei o kakunin shimashou - To protect anonymity, let's check the privacy settings",
    "彼は匿名で寄付をした Kare wa tokumei de kifu o shita - He made a donation anonymously",
    "匿名の通報者が事件の解決に役立った Tokumei no tsuuhousha ga jiken no kaiketsu ni yakudatta - An anonymous tipster helped solve the case",];
export const tenExample6 = [
    "私の制服は紺色です Watashi no seifuku wa koniro desu - My uniform is navy blue",
    "紺色の靴を買いたいです Koniro no kutsu o kaitai desu - I want to buy navy blue shoes",
    "彼は紺色のネクタイを着ています Kare wa koniro no nekutai o kiteimasu - He is wearing a navy blue tie",
    "紺色は私の好きな色です Koniro wa watashi no suki na iro desu - Navy blue is my favorite color",
    "紺色のジャケットを見つけました Koniro no jaketto o mitsukemashita - I found a navy blue jacket",
    "この紺色のカバンは素敵ですね Kono koniro no kaban wa suteki desu ne - This navy blue bag is lovely, isn't it?",
    "彼女は紺色のスカートを着ています Kanojo wa koniro no sukāto o kiteimasu - She is wearing a navy blue skirt",
    "紺色の空はとても美しいです Koniro no sora wa totemo utsukushii desu - The navy blue sky is very beautiful",
    "紺色の花瓶を机の上に置いてください Koniro no kabin o tsukue no ue ni oite kudasai - Please put the navy blue vase on the desk",
    "紺色のストールを買いました Koniro no sutōru o kaimashita - I bought a navy blue scarf",
];
export const tenExample7 = [
    "帽子をかぶって外出しましょう Bōshi o kabutte gaishutsu shimashou - Let's wear hats and go outside",
    "彼はいつも帽子をかぶっています Kare wa itsumo bōshi o kabutteimasu - He always wears a hat",
    "その帽子はとてもかわいいですね Sono bōshi wa totemo kawaii desu ne - That hat is very cute",
    "帽子を買うために店に行きます Bōshi o kau tame ni mise ni ikimasu - I'm going to the store to buy a hat",
    "帽子を取ると、髪がぱさぱさになります Bōshi o toru to, kami ga pasapasa ni narimasu - When I take off my hat, my hair gets messy",
    "この帽子は夏にぴったりです Kono bōshi wa natsu ni pittari desu - This hat is perfect for summer",
    "帽子を洗濯する方法を教えてください Bōshi o sentaku suru hōhō o oshiete kudasai - Please teach me how to wash a hat",
    "彼女は帽子が似合いますね Kanojo wa bōshi ga niaimasu ne - Hats suit her well",
    "この帽子は日差しを遮るのに良さそうです Kono bōshi wa hizashi o saegiru noni yosasou desu - This hat looks good for blocking the sunlight",
    "帽子を被ると、寒さから守られます Bōshi o kaburu to, samusa kara mamoraremasu - Wearing a hat protects you from the cold",
];
export const tenExample8 = [
    "鼓を演奏するのが好きです Tsuzumi o ensō suru no ga suki desu - I like playing the drum",
    "彼は鼓の音に合わせて踊ります Kare wa tsuzumi no oto ni awasete odorimasu - He dances to the beat of the drum",
    "鼓のリズムに合わせて歩く Tsuzumi no rizumu ni awasete aruku - Walk to the rhythm of the drums",
    "鼓を叩くとストレスが解消されます Tsuzumi o tataku to sutoresu ga kaishō saremasu - Playing the drum helps relieve stress",
    "仲間の支持は彼を鼓舞している Nakama no shiji wa kare o kobu shiteiru - The support of his friends is encouraging him",
    "不安で鼓動が速くなることがある Fuan de kodō ga hayaku naru koto ga aru - Sometimes anxiety makes the heartbeat faster",
    "突然の大きな音で鼓膜が痛んだ Totsuzen no ōkina oto de komaku ga itanda - My eardrums hurt from the sudden loud noise",
    "先生は生徒たちを励まし鼓した Sensei wa seito-tachi o hagemashi odoshita - The teacher encouraged and motivated the students",
    "彼女の言葉は私に勇気を鼓舞した Kanojo no kotoba wa watashi ni yūki o kobu shita - Her words encouraged me and gave me courage",
    "鼓を手に取り、こころゆくまで演奏しました Tsuzumi o te ni tori, kokoro yuku made ensō shimashita - I took the drum in my hands and played to my heart's content",
];
export const tenExample9 = [
    "口の中を潤すために水を飲んだ Kuchi no naka o uruosu tame ni mizu o nonda - I drank water to moisten my mouth",
    "花が雨で潤った Hana ga ame de uruotta - The flowers were moistened by the rain",
    "潤いのある空気が気持ちいい Uruoi no aru kūki ga kimochi ī - The air with moisture feels pleasant",
    "ボディローションを使って肌を潤わせる Bodi rōshon o tsukatte hada o uruwaseru - Use body lotion to moisturize your skin",
    "雨が地面を潤してくれた Ame ga jimen o uruoshite kureta - The rain moistened the ground for us",
    "自転車のチェーンに潤滑剤を塗りました Jitensha no chēn ni junkatsuzai o nurimashita - I applied lubricant to the bicycle chain",
    "この地域は水が潤沢です Kono chiiki wa mizu ga junsaku desu - This area has an abundant water supply",
    "その地域は自然資源が潤沢で有名です Sono chiiki wa shizen shigen ga junsaku de yuumei desu - That region is famous for its abundant natural resources",
    "工場の機械には定期的に潤滑油を補充する必要があります Koujou no kikai ni wa teikiteki ni junkatsuyu o hokan suru hitsuyou ga arimasu - The machines in the factory need regular replenishment of lubricating oil",
    "農場では、作物に必要な水が潤沢に供給されます Noujou de wa, sakumotsu ni hitsuyou na mizu ga junsaku ni kyoukyuu saremasu - The farm has abundant water supply for the crops",
    
];
export const tenExample10 = [
    "この夜は豪華な宴が開かれる予定です Kono yoru wa gouka na utage ga hirakareru yotei desu - A lavish feast is scheduled for tonight",
    "宴の席で楽しい時間を過ごしました Utage no seki de tanoshii jikan o sugoshimashita - I had a great time at the banquet",
    "彼の誕生日は宴を開くのに最適な日です Kare no tanjoubi wa utage o hiraku noni saiteki na hi desu - His birthday is the perfect day for a feast",
    "会社の年末の宴はとても楽しいです Kaisha no nenmatsu no en wa totemo tanoshii desu - The company's year-end banquet is very enjoyable",
    "彼らは毎年、家族で宴を開いています Karera wa maitoshi, kazoku de en o hiraiteimasu - They hold a family banquet every year",
    "友達との宴はいつも盛り上がります Tomodachi to no en wa itsumo moriagari masu - Banquets with friends are always lively",
    "豪華な宴で美味しい料理を楽しみました Gouka na en de oishii ryouri o tanoshimimashita - I enjoyed delicious dishes at a lavish banquet",
    "今夜は家族と一緒に賑やかな宴を楽しみます Konya wa kazoku to issho ni nigiyaka na en o tanoshimimasu - Tonight, I'll enjoy a lively banquet with my family",
    "先週の結婚式の宴は素晴らしかったですね Senshuu no kekkonshiki no en wa subarashikatta desu ne - The banquet at last week's wedding was wonderful, wasn't it",
    "彼の功績を祝うために宴を計画しています Kare no kouseki o iwau tame ni en o keikaku shiteimasu - We are planning a banquet to celebrate his achievements",
];
export const tenExample11 = [
    "彼は国に貢献するために尽力しています Kare wa kuni ni kouken suru tame ni jinryoku shiteimasu - He is making efforts to contribute to the country",
    "古代の王たちは貢物を差し出すことが求められました Kodai no ō-tachi wa koumotsu o sashidasu koto ga motomeraremashita - Ancient kings were required to present tributes",
    "彼女は毎月、慈善団体に貢献しています Kanojo wa maitsuki, jizen dantai ni kouken shiteimasu - She contributes to a charity organization every month",
    "社会への貢献は多岐にわたることが重要です Shakai e no kouken wa takawa ni wataru koto ga juuyou desu - Contributions to society come in various forms and are essential",
    "貢物は古代の文化交流で重要な役割を果たしました Koumotsu wa kodai no bunka kouryuu de juuyou na yakuwari o hatashimashita - Tributes played a significant role in ancient cultural exchanges",
    "彼の貢献がプロジェクトの成功につながりました Kare no kouken ga purojekuto no seikou ni tsunagarimashita - His contribution led to the success of the project",
    "社会に貢献することは大切なことです Shakai ni kouken suru koto wa taisetsu na koto desu - Contributing to society is important",
    "彼女は環境保護に貢献しています Kanojo wa kankyou hogo ni kouken shiteimasu - She is contributing to environmental conservation",
    "古代の王国では、貢納が課せられていました Kodai no oukoku de wa, kounou ga kasesareteimashita - Ancient kingdoms imposed tribute payments",
    "貢納が国の財政に影響を与えました Kounou ga kuni no zaisei ni eikyou o ataemashita - Tribute payments affected the country's finances",
];
export const tenExample12 = [
    "最近、彼は痩せてきたね Saikin, kare wa yasete kita ne - Lately, he has become thinner",
    "健康的に痩せるために運動を始めました Kenkouteki ni yaseru tame ni undou o hajimemashita - I started exercising to become thin in a healthy way",
    "ストレスが原因で痩せてしまった Sutoresu ga gen'in de yasete shimatta - I became thin due to stress",
    "彼女はダイエットで痩せたそうです Kanojo wa daietto de yaseta sou desu - She seems to have become thin through dieting",
    "彼は病気で急に痩せてしまった Kare wa byouki de kyuu ni yasete shimatta - He became thin suddenly due to illness",
    "彼女は痩身な体型を保つために運動しています Kanojo wa soushin na taigata o tamotsu tame ni undou shiteimasu - She exercises to maintain a slim figure",
    "あのモデルは痩身で知られています Ano moderu wa soushin de shirareteimasu - That model is known for her slim figure",
    "痩せ肉は低脂肪でヘルシーな選択です Yase niku wa teishibou de herushii na sentaku desu - Lean meat is a healthy and low-fat choice",
    "痩身を目指して、毎日ジョギングをしています Soushin o mezashite, mainichi jogingu o shiteimasu - Aiming for a slim figure, I jog every day",
    "彼女は痩身な体型を保つために運動しています Kanojo wa soushin na taigata o tamotsu tame ni undou shiteimasu - She exercises to maintain a slim figure",
];
export const tenExample13 = [
    "彼は私に大きな痩せてきたね恩を受けました Kare wa watashi ni ooki na on o ukemashita - He received a great favor from me",
    "痩せてきたね恩を仇で返すことはできません On o adade kaesu koto wa dekimasen - You can't repay kindness with ingratitude",
    "彼は痩せてきたね恩を忘れることはありません Kare wa on o wasureru koto wa arimasen - He never forgets a favor",
    "痩せてきたね恩には痩せてきたね恩で返すのが礼儀です On ni wa on de kaesu no ga reigi desu - It's proper etiquette to repay a favor with a favor",
    "その人はいつも痩せてきたね恩を忘れずに生きています Sono hito wa itsumo on o wasurezu ni ikiteimasu - That person always lives without forgetting favors",
    "彼女は私に痩せてきたね恩を感じさせることができる人です Kanojo wa watashi ni on o kanjisaseru koto ga dekiru hito desu - She's someone who can make me feel grateful",
    "痩せてきたね恩は忘れたりしません On wa wasuretari shimasen - Favors should not be forgotten",
    "その人は多くの人々に痩せてきたね恩を着せています Sono hito wa ooku no hitobito ni on o kiseteimasu - That person has shown kindness to many people",
    "痩せてきたね恩を仇で返さないように心がけています On o adade kae sanai you ni kokorogaketeimasu - I try not to repay kindness with ingratitude",
    "痩せてきたね恩は大切にしなければいけません On wa taisetsu ni shinakereba ikemasen - We must treasure favors",
];
export const tenExample14 = [
    "彼は秘密裏に計画を謀っていた Kare wa himitsurani keikaku o hakatteita - He was secretly plotting a plan",
    "敵は次なる一手を謀っているかもしれません Teki wa tsuginaru itte o hakatteiru kamoshiremasen - The enemy may be plotting their next move",
    "陰湿な陰謀を謀る者がいるかもしれない Inshitsu na inbou o hakaru mono ga iru kamoshirenai - There might be someone plotting a malicious conspiracy",
    "彼は政敵を謀るために情報を集めている Kare wa seihoku o hakaru tame ni jouhou o atsumeteiru - He is gathering information to plot against his political rival",
    "その犯罪者は狡猾な謀を巡らしている Sono hanzai-sha wa koukatsu na bou o megurashiteiru - The criminal is weaving cunning schemes",
    "彼は邪悪な謀を企んでいるようだ Kare wa jaaku na bou o takurandeiru you da - It seems like he's planning something wicked",
    "政治の世界は裏で様々な謀が渦巻いている Seiji no sekai wa ura de samazama na bou ga uzumaiteiru - The world of politics is swirling with various plots behind the scenes",
    "そのグループは大胆な謀を実行した Sono guruupu wa daitan na bou o jikkou shita - The group executed a bold plot",
    "事件には悪賢い謀があるようです Jiken niwa warukashikoi bou ga aru you desu - It seems there's a cunning plot behind the incident",
    "彼は自分の利益のために謀をめぐらしている Kare wa jibun no rieki no tame ni bou o megurashiteiru - He is scheming for his own benefit",
];
export const tenExample15 = [
    "その風車は風の力で旋回しています Sono fuusha wa kaze no chikara de senkai shiteimasu - That windmill is rotating with the power of the wind",
    "ダンサーの旋律は美しい踊りを彩ります Dansaa no senritsu wa utsukushii odori o irodorimasu - The dancer's rhythm enhances the beauty of the dance",
    "旋回する飛行機の音が聞こえました Senkai suru hikouki no oto ga kikoemashita - I heard the sound of a rotating airplane",
    "時計の針が旋回し続けています Tokei no hari ga senkai shi tsuzuketeimasu - The clock hands continue to rotate",
    "その映画は一つの物語を旋律しています Sono eiga wa hitotsu no monogatari o kaiten shiteimasu - That movie revolves around one story",
    "色彩の旋律が絵画の美しさを際立たせます Shikisai no senritsu ga kaiga no utsukushisa o kiwadatase masu - The color scheme accentuates the beauty of the painting",
    "地球の自転は一日に一度旋回します Chikyuu no jituen wa ichinichi ni ichido senkai shimasu - The Earth rotates once a day",
    "彼の話は主題を旋回しました Kare no hanashi wa shudai o senkai shimashita - His story revolved around the main theme",
    "旋回するカルーセルは子供たちの楽しみです Senkai suru karuusel wa kodomotachi no tanoshimi desu - The rotating carousel is a delight for children",
    "風船は空でゆっくりと旋回していました Fuusen wa sora de yukkuri to senkai shiteimashita - The balloon was slowly rotating in the sky",
];
export const tenExample16 = [
    "盾を持って、彼は戦いに備えた Tate o motte, kare wa tatakai ni sonaeta - He prepared for battle with a shield in hand",
    "古代の戦士たちは盾を使って身を守った Kodai no senshi-tachi wa tate o tsukatte mi o mamotta - Ancient warriors protected themselves using shields",
    "盾は攻撃から身を守るための大切な道具です Tate wa kougeki kara mi o mamoru tame no taisetsu na dougu desu - A shield is an important tool for protecting oneself from attacks",
    "彼は信念を盾にして立ち向かった Kare wa shinnen o tate ni shite tachimukatta - He faced it with his beliefs as his shield",
    "盾を持つことは自己防衛の手段です Tate o motsu koto wa jiko bouei no shudan desu - Holding a shield is a means of self-defense",
    "戦士たちは盾を前に立てて進んだ Senshi-tachi wa tate o mae ni tatete susunda - The warriors advanced, holding their shields in front of them",
    "盾は戦場での生存を助ける役割を果たします Tate wa senjou de no seizon o tasukeru yakuwari o hatashimasu - Shields play a role in aiding survival on the battlefield",
    "その盾は重厚な作りでした Sono tate wa juukou na tsukurideshita - That shield was made with a sturdy build",
    "彼は盾を携えて旅をすることに決めた Kare wa tate o tazusaete tabi o suru koto ni kimeta - He decided to travel carrying a shield",
    "盾を持つことは危険から身を守る手段です Tate o motsu koto wa kiken kara mi o mamoru shudan desu - Holding a shield is a means to protect oneself from danger",
];
export const tenExample17 = [
    "寮生活は新しい友達をたくさん作る機会です Ryou seikatsu wa atarashii tomodachi o takusan tsukuru kikai desu - Dorm life is an opportunity to make many new friends",
    "大学の寮には共有のキッチンがあります Daigaku no ryou ni wa kyoyuu no kitchin ga arimasu - The university dormitory has a shared kitchen",
    "寮での生活は自立心を育てるいい機会です Ryou de no seikatsu wa jiritsushin o sodateru ii kikai desu - Living in a dormitory is a good opportunity to foster independence",
    "彼は学校の寮に住んでいます Kare wa gakkou no ryou ni sundeimasu - He lives in the school dormitory",
    "寮には共有のバスルームもあります Ryou ni wa kyoyuu no basuruumu mo arimasu - There is also a shared bathroom in the dormitory",
    "大学に入るときに、寮に住むことを選びました Daigaku ni hairu toki ni, ryou ni sumu koto o erabimashita - When entering college, I chose to live in the dormitory",
    "寮での生活は貴重な経験になることが多いです Ryou de no seikatsu wa kichou na keiken ni naru koto ga ooi desu - Life in the dormitory often becomes a valuable experience",
    "この寮は施設が整っていて快適です Kono ryou wa shisetsu ga tootteite kaiteki desu - This dormitory is well-equipped and comfortable",
    "学校の寮は学生の間で人気があります Gakkou no ryou wa gakusei no aida de ninki ga arimasu - The school dormitory is popular among students",
    "寮生活は新しい環境に適応する手助けになります Ryou seikatsu wa atarashii kankyou ni tekiou suru tedasuke ni narimasu - Dorm life helps adapt to new environments",
];
export const tenExample18 = [
    "そのナイフの刃が鋭いです Sono naifu no ha ga surudoi desu - The blade of that knife is sharp",
    "刃物を使うときは注意が必要です Hamono o tsukau toki wa chuui ga hitsuyou desu - Caution is necessary when using sharp objects",
    "彼は刃物の取り扱いに慣れています Kare wa hamono no toriatsukai ni nareteimasu - He is familiar with handling blades",
    "斧の刃を研いでください Ono no ha o toide kudasai - Please sharpen the blade of the axe",
    "刃のないナイフは使いにくいです Ha no nai naifu wa tsukai nikui desu - A knife without a blade is difficult to use",
    "包丁の刃が欠けてしまいました Houchou no ha ga kakete shimaimashita - The blade of the kitchen knife chipped",
    "彼は刃物を使う際に常に慎重です Kare wa hamono o tsukau sai ni tsune ni shinchou desu - He is always cautious when using blades",
    "その刃は切れ味がよくないです Sono ha wa kireaji ga yoku nai desu - That blade isn't very sharp",
    "刃を持つことは責任が伴います Ha o motsu koto wa sekinin ga tomonaimasu - Having a blade comes with responsibility",
    "バリカンの刃を交換する必要があります Barikan no ha o koukan suru hitsuyou ga arimasu - It's necessary to replace the blade of the hair clipper",
];
export const tenExample19 = [
    "その新聞社は文化の啓蒙活動を行っています Sono shinbunsha wa bunka no keimou katsudou o okonatteimasu - That newspaper company is engaged in cultural enlightenment activities",
    "啓蒙活動は知識を広めるために重要です Keimou katsudou wa chishiki o hirogeru tame ni juuyou desu - Enlightenment activities are important for spreading knowledge",
    "彼の教育政策は国民の啓発を目指しています Kare no kyouiku seisaku wa kokumin no keihatsu o mezashiteimasu - His educational policy aims at enlightening the citizens",
    "啓発活動は社会問題を解決するのに役立ちます Keihatsu katsudou wa shakai mondai o kaiketsu suru noni yakudachimasu - Awareness campaigns help in solving social issues",
    "啓蒙運動は社会の進歩に寄与します Keimou undou wa shakai no shinpo ni kiyoshimasu - Enlightenment movements contribute to the progress of society",
    "彼は新しい技術の啓蒙に尽力しています Kare wa atarashii gijutsu no keimou ni jinryoku shiteimasu - He is making efforts to enlighten people about new technologies",
    "啓蒙活動は多くの人々に影響を与えました Keimou katsudou wa ooku no hitobito ni eikyou o ataemashita - Enlightenment activities have influenced many people",
    "その組織は啓蒙的なイベントを開催しています Sono soshiki wa keimouteki na ibento o kaisai shiteimasu - That organization is hosting an enlightening event",
    "啓蒙活動は社会的変革を促進する役割を果たします Keimou katsudou wa shakaiteki henkaku o sokushin suru yakuwari o hatashimasu - Enlightenment activities play a role in promoting social change",
    "啓蒙運動は人々の意識を変えることができます Keimou undou wa hitobito no ishiki o kaeru koto ga dekimasu - Enlightenment movements can change people's consciousness",
];
export const tenExample20 = [
    "彼の勇敢な行動は多くの誉れを受けました Kare no yuukan na koudou wa ooku no homare o ukemashita - His brave actions received much honor",
    "誉れ高い功績により、その将軍は武士たちから敬意を受けた Homare-takai kouseki ni yori, sono shougun wa bushi-tachi kara keii o uketa - Due to his honorable achievements, the general gained respect from the warriors",
    "彼の卓越した才能は多くの誉れをもたらした Kare no takuetsu shita sainou wa ooku no homare o motarashita - His outstanding talent brought much honor",
    "その作品は国際的な賞を受賞し、大きな誉れを受けました Sono sakuhin wa kokusaiteki na shou o jushou shi, ookina homare o ukemashita - The work received international awards, earning great honor",
    "彼の人間性に対する誉れは広く知られています Kare no ningensei ni taisuru homare wa hiroku shirareteimasu - The honor for his character is widely known",
    "誉れ高い行為に感動し、彼に感謝の意を表明した Homare-takai koui ni kandou shi, kare ni kansha no i o hyoumei shita - Touched by the honorable act, they expressed gratitude to him",
    "その文学賞は彼女に大いなる誉れをもたらしました Sono bungaku shou wa kanojo ni ooinaru homare o motarashimashita - The literary award brought great honor to her",
    "地元の英雄は市民から誉れ高い評価を受けています Jimoto no eiyuu wa shimin kara homare-takai hyouka o uketeimasu - The local hero is highly esteemed by the citizens",
    "彼の成功に対して、上司は彼を褒めました Kare no seikou ni taishite, joushi wa kare o homerimashita - The boss praised him for his success",
    "子供が良い行動をしたら、必ず褒めてあげてください Kodomo ga ii koudou o shitara, kanarazu homeru teagete kudasai - Whenever a child behaves well, be sure to praise them",
];



